### ISSUE TITLE
不会搭建运行环境

### ISSUE THREAD

**Issue by Felictycf** [webzhd/code-game#26]
大哥我非常喜欢你的这个项目,我自己也想写这样类型的,我是主后端,对前端技术就会的不多,这个里面的react的组件库我也不会安装,我想学完react之后基于你的项目自己开发更多类型的打字练习,特别是英语,而且想把翻译做的更好,加入英语文章等等有趣的学习内容,
后期想做多人pk游戏,不会搭建运行环境,大哥是否可以在readme里面说明一下,谢谢,可以把技术栈说说吗?

**Comment by webzhd** [comment]
想法挺好的，以下是开发环境搭建方式，遇到更细节的问题可以问身边的前端或自行百度/Google，教程很多。

1. 安装nodejs
2. git clone该项目
3. npm install 安装依赖
4. npm run dev 运行开发环境
已更新 README 如有问题，再与我联系
