### ISSUE TITLE
npm run dev 出现 failed to compile

### ISSUE THREAD

**Issue by Felictycf** [webzhd/code-game#28]
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

Compiling...
Files successfully emitted, waiting for typecheck results...

Files successfully emitted, waiting for typecheck results...

Failed to compile.

/opt/react-code-game-master/node_modules/pretty-format/build/index.d.ts
TypeScript error in /opt/react-code-game-master/node_modules/pretty-format/build/index.d.ts(7,13):
'=' expected.  TS1005

     5 |  * LICENSE file in the root directory of this source tree.
     6 |  */
  >  7 | import type { NewPlugin, Options, OptionsReceived } from './types';
       |             ^
     8 | export type { Colors, CompareKeys, Config, Options, OptionsReceived, OldPlugin, NewPlugin, Plugin, Plugins, PrettyFormatOptions, Printer, Refs, Theme, } from './types';
     9 | export declare const DEFAULT_OPTIONS: Options;
    10 | /**

上次我运行可以(大约20天前),但是这次运行失败了,是不是npm安装的node_modul库有问题呀

**Comment by webzhd** [comment]
删除.lock文件和node_modules文件夹重新执行 npm install 安装依赖
